apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
    name: k8s-gateway
    namespace: networking
spec:
    interval: 30m
    chart:
        spec:
            chart: k8s-gateway
            version: 2.1.0
            sourceRef:
                kind: HelmRepository
                name: k8s-gateway
                namespace: flux-system
    maxHistory: 2
    install:
        remediation:
            retries: 3
    upgrade:
        cleanupOnFail: true
        remediation:
            retries: 3
    uninstall:
        keepHistory: false
    values:
        fullnameOverride: k8s-gateway
        domain: ${SECRET_DOMAIN}
        ttl: 1
        service:
            type: LoadBalancer
            port: 53
            annotations:
                io.cilium/lb-ipam-ips: ENC[AES256_GCM,data:+Gws+l2sM5GDBlfT8s4=,iv:fOnuA7gwI8XEU+FKhpkKLb/paMjX5CLaNjStvT1zBxY=,tag:r5M/vHgVC/8G0/nKk49RmA==,type:str]
            externalTrafficPolicy: Cluster
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pr4mejfd5gvq7fvkhgs534dftetx83564rj4j2y0hat6eucjl49qp60ag5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMnN3L3UvQkxGcXhsQUd1
            aVE2VGdqSncxVWVKazVjTUlQRDZiZGM2bFNRClZqcGdYOGRhcnFrUHFTOEIvbStS
            ZkdQL21yOGhDU2tJYndpQ2dVMVFDREUKLS0tIGExc3B4VFRBb3RoaFJUUUZCQWJM
            M05kNE5nNjlWTEZYbGpyblpqRmR0T2MKwJGllznfM5JSyU99QHXdAr1UnIimlERA
            sKy6cuvaANgfa0bDxCtaUPStDVJscHhF5zrVifaVpx83drXCsfZITQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-01T23:23:53Z"
    mac: ENC[AES256_GCM,data:VeFtVYPsoAY6JYhhSlaD6Q5PCy+tCfeDs0L2g+Q3O4O0IZfPLETd2BI+pdzytxaD94dQTDrVi8L1oSgbti/FNoaNIKCjS66OfafjzdbYWnYj2G+TaoDhy7QJmp8hCKYQrMmFcBa4ilQwPHdsYc1wIsQaaX9tBYHuDB8dPeymrM4=,iv:TQ5AbYAlvsA6sFVW4j+LvSFEbRGUV1slAFjymBq8DSc=,tag:aYRhPfRS9I3aKTN10aZEcQ==,type:str]
    pgp: []
    encrypted_regex: lb-ipam-ips
    version: 3.8.0
