---
galaxy_info:
  author: Josh
  description: common tasks
  license: BSD-3-Clause

  min_ansible_version: 2.8

  platforms:
  - name: Fedora
    versions:
    - all
  - name: Debian
    versions:
    - all

  galaxy_tags: []

dependencies: []
