---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 10m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        type: statefulset
      containers:
        main:
          image:
            repository: esphome/esphome
            tag: 2023.10.6
          env:
            ESPHOME_DASHBOARD_USE_PING: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
    service:
      main:
        ports:
          http:
            port: 6052
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host esphome.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: wildcard-cert-tls
    persistence:
      config:
        enabled: true
        existingClaim: esphome-config
        globalMounts:
          - path: /config
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
      limits:
        memory: 4Gi
    metrics:
      enabled: true
