---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-esphome
  namespace: default
  labels:
    app.kubernetes.io/name: &name esphome
    app.kubernetes.io/instance: *name
spec:
  storageClassName: nfs-esphome
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_PATH}/esphome"
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: nfs-esphome
