apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-webhook-henet-secret
    namespace: cert-manager
data:
    apikey: ENC[AES256_GCM,data:WIYcbQik1tfzNdkJf+rHWQ==,iv:L2D5SoZvMSyosU892IeZefp+g1gkU95c5YicSZulCGg=,tag:VmO6BplFaH5EuIP2D6/9Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pr4mejfd5gvq7fvkhgs534dftetx83564rj4j2y0hat6eucjl49qp60ag5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjY1c1Q0S3JqVVdCdW1s
            RmNFZUZVN2xtMjdpMC96RU9BdUVzdXJ0c0NjCk1JalhMZmlac056VFRDY2t0ZlRx
            b2k1aVFqSm9xRTg4NnhyazdaZWN4MHMKLS0tIE00dnlGbnVEL2xCS0RSanNUeDNQ
            RHJvNDNrSWw5N240Tk1MRVpGYVI4TXMKSD3oE1p/LxkOdrPwPcUgvgL3XDIBApUS
            A6ScvnodtFjV1OWeI4F0MOJRDodJudv6vSYBDAgCmMclTE2oJdizUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-02T17:33:35Z"
    mac: ENC[AES256_GCM,data:Hvd5hzNKqEVAETrKm1lgppIPKFFLiLoE4F+nNf8NdxuiaJ/7NXjMJhUtgZAkFN3LqkTgoyO4dHczszg3g+cW2Qs6K9g1o5EtOzG3BVN5nypGLJu+jJHg4YBxD2UfhdnbZIQsBl9oeMN/PF5VLCUYs3nkPtGmB6KWFJvpkFtC0+k=,iv:as6kLjhwdPXhbu7ufw6fAUD6iHiH1WiSW5GPlZY7kzU=,tag:dELr5N1mhpXggSQHG4sMoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
