---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-redis
  namespace: security
spec:
  target:
    name: authentik-redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_REDIS_PASSWORD: "{{ .authentik_redis_password }}"
  data:
    - secretKey: authentik_redis_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: authentick redis
        property: password
