# Use 120 for line length
MD013:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: false
  tables: true
  headings: true
  headers: true
  strict: false
  stern: false
