---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2023-11-11T08-14-41Z
            args:
              - server
              - /data
              - --console-address
              - :9001
            env:
              TZ: America/New_York
              MINIO_UPDATE: "off"
              MINIO_PROMETHEUS_URL: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
              MINIO_PROMETHEUS_JOB_ID: minio
              MINIO_PROMETHEUS_AUTH_TYPE: public
              MINIO_BROWSER_REDIRECT_URL: https://minio.${SECRET_DOMAIN}
              MINIO_SERVER_URL: https://s3.${SECRET_DOMAIN}
              MINIO_API_CORS_ALLOW_ORIGIN: https://minio.${SECRET_DOMAIN},https://s3.${SECRET_DOMAIN}
              MINIO_ROOT_USER:
                valueFrom:
                  secretKeyRef:
                    name: minio-secrets
                    key: MINIO_ROOT_USER
              MINIO_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: minio-secrets
                    key: MINIO_ROOT_PASSWORD
            resources:
              requests:
                cpu: 5m
                memory: 128M
            securityContext:
              privileged: true
              runAsUser: 0

    service:
      main:
        ports:
          http:
            port: 9001
          s3:
            port: 9000

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: "minio.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
          - host: "s3.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: s3

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: nfs-minio
        globalMounts:
          - path: /data
