apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-minio
  namespace: storage
spec:
  storageClassName: minio
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "/volume2/nvme/s3"
  mountOptions:
  - nfsvers=4.1
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
