---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-login
spec:
  provider:
    webhook:
      url: "http://bitwarden.kube-system.svc:8087/list/object/items?search={{ .remoteRef.key }}"
      headers:
        Content-Type: application/json
      result:
        jsonPath: "$.data.data[0].login.{{ .remoteRef.property }}"
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-fields
spec:
  provider:
    webhook:
      url: "http://bitwarden.kube-system.svc:8087/list/object/items?search={{ .remoteRef.key }}"
      result:
        jsonPath: "$.data.data[0].fields[?@.name==\"{{ .remoteRef.property }}\"].value"
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-notes
spec:
  provider:
    webhook:
      url: "http://bitwarden.kube-system.svc:8087/list/object/items?search={{ .remoteRef.key }}"
      result:
        jsonPath: "$.data.data[0].notes"
