---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-aggregator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: vector-aggregator-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GEOIPUPDATE_ACCOUNT_ID: "{{ .account_id }}"
        GEOIPUPDATE_LICENSE_KEY: "{{ .license_key }}"
  data:
    - secretKey: account_id
      remoteRef:
        key: maxmind api
        property: username
    - secretKey: license_key
      remoteRef:
        key: maxmind api
        property: password
