---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitwarden-eso-provider
  namespace: flux-system
spec:
  interval: 2h
  url: https://small-hack.github.io/bitwarden-eso-provider
