---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik.yaml
  - ./bitnami.yaml
  - ./bitwarden-eso.yaml
  - ./bjw-s.yaml
  - ./cert-manager-webhook-he.yaml
  - ./cert-manager-webhook-henet.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./influxdb.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./prometheus-community.yaml
  - ./stakater.yaml
  - ./weaveworks.yaml
