---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: emqx-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin_password: "{{ .admin_password }}"
        user_1_password: "{{ .user_password }}"
  data:
    - secretKey: user_password
      remoteRef:
        key: emqx credentials
        property: user_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
    - secretKey: admin_password
      remoteRef:
        key: emqx credentials
        property: password
