---
# main task file for ignition
- name: Generate ignition file when ignition_dest is provided
  when: ignition_dest is defined
  command: butane --pretty --strict -o {{ ignition_dest }}
  args:
    stdin: '{{ ignition_butane_config | to_yaml }}'

- name: Output butane file to stdout when ignition_dest is not provided
  when: ignition_dest is not defined
  ansible.builtin.debug:
    msg: |
      {{ ignition_butane_config | to_yaml }}
