apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-terraform
  namespace: security
data:
  terraform.yaml: |
    apiVersion: blueprints.goauthentik.io/v1
    kind: Blueprint
    metadata:
      name: terraform-user
    spec:
      models:
        - model: authentik_core.user
          state: present
          identifiers:
            username: npe.terraform
          attrs:
            name: Terraform
            password: !Env AUTHENTIK_TERRAFORM_PASSWORD
        - model: authentik_core.token
          state: present
          identifiers:
            identifier: !Env AUTHENTIK_TERRAFORM_CLIENT_ID
          attrs:
            key: !Env AUTHENTIK_TERRAFORM_TOKEN
            user: !KeyOf npe.terraform
            intent: api
