---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-logen
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        authentik_secret_key: "{{ .authentik_secret_key }}"
  data:
    - secretKey: authentik_secret_key
      remoteRef:
        key: authentik credentials
        property: password
