---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2023.8.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    annotations:
      secret.reloader.stakater.com/reload: authentik-secret,authentik-redis-secret

    initContainers:
      init-db:
        image:
          repository: ghcr.io/onedr0p/postgres-init
          tag: 14
          pullPolicy: IfNotPresent
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: authentik-secret

    authentik:
      log_level: info
      email:
        enabled: false
      error_reporting:
        enabled: false
        send_pii: false

    envValueFrom:
      AUTHENTIK_SECRET_KEY:
        secretKeyRef:
          name: authentik-secret
          key: AUTHENTIK_SECRET_KEY
      AUTHENTIK_POSTGRESQL__HOST:
        secretKeyRef:
          name: authentik-secret
          key: AUTHENTIK_POSTGRESQL__HOST
      AUTHENTIK_POSTGRESQL__NAME:
        secretKeyRef:
          name: authentik-secret
          key: AUTHENTIK_POSTGRESQL__NAME
      AUTHENTIK_POSTGRESQL__USER:
        secretKeyRef:
          name: authentik-secret
          key: AUTHENTIK_POSTGRESQL__USER
      AUTHENTIK_POSTGRESQL__PASSWORD:
        secretKeyRef:
          name: authentik-secret
          key: AUTHENTIK_POSTGRESQL__PASSWORD
      AUTHENTIK_REDIS__URL:
        secretKeyRef:
          name: authentik-secret
          key: AUTHENTIK_REDIS__URL

    ingress:
      enabled: true
      ingressClassName: external-nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      hosts:
        - host: &host auth.${SECRET_DOMAIN}
          paths:
            - path: /
      tls:
        - hosts:
            - *host

    postgresql:
      enabled: false

    prometheus:
      rules:
        create: true
      serviceMonitor:
        create: true

    redis:
      enabled: false
