---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - ./configmap.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./helmrepository.yaml
commonLabels:
  app.kubernetes.io/name: authentik
  app.kubernetes.io/instance: authentik
