apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          webhook:
            groupName: "${SECRET_DOMAIN}"
            solverName: hurricane-electric
            config:
              secretName: cert-manager-webhook-henet-secret
              apiUrl: https://dyn.dns.he.net
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          webhook:
            groupName: "${SECRET_DOMAIN}"
            solverName: hurricane-electric
            config:
              secretName: cert-manager-webhook-henet-secret
              apiUrl: https://dyn.dns.he.net
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
