apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          webhook:
            groupName: "acme-challenge.${SECRET_DOMAIN}"
            solverName: he
            config:
              method: "dynamic-dns"

              apiKeySecretRef:
                name: cert-manager-webhook-henet-secret
                namespace: "cert-manager"
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_ACME_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          webhook:
            groupName: "acme-challenge.${SECRET_DOMAIN}"
            solverName: he
            config:
              method: "dynamic-dns"

              apiKeySecretRef:
                name: cert-manager-webhook-henet-secret
                namespace: "cert-manager"
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
