---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-unifi
  namespace: default
spec:
  storageClassName: unifi
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_PATH}/unifi"
  mountOptions:
  - nfsvers=4.1
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
  namespace: default
  labels:
    app.kubernetes.io/name: &name unifi
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: unifi
  resources:
    requests:
      storage: 10Gi
