---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre-flux kustomizations
  - ./namespace.yaml
  # flux kustomizations
  - ./emqx/ks.yaml
  - ./esphome/ks.yaml
  - ./home-assistant/ks.yaml
  - ./unifi/ks.yaml
  - ./zwave-js-ui/ks.yaml
