---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre-flux kustomizations
  - ./namespace.yaml
  # flux kustomizations
  - ./esphome/ks.yaml
  - ./home-assistant/ks.yaml
  # disabled to upgrade from 1.5.1 to 2.2.0
  # - ./unifi/ks.yaml
  - ./zwave-js-ui/ks.yaml
