---
# Ansible tasks for setting up Fedora
- name: Ensure SELinux Enforcing
  become: true
  become_user: root
  selinux:
    policy: targeted
    state: enforcing

- name: Enable container_manage_cgroup for running systemd in podman containers
  become: true
  become_user: root
  seboolean:
    name: container_manage_cgroup
    state: true
    persistent: true
