---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-emqx
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/default/emqx/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
  dependsOn:
    - name: cluster-apps-external-secrets-bitwarden
