---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: cluster-user-auth # weave-gitops expects this name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: weave credentials
        property: username
    - secretKey: password
      remoteRef:
        key: weave credentials
        property: password
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-oidc-auth
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: oidc-auth # weave-gitops expects this name
    template:
      data:
        clientID: "{{ .client_id }}"
        clientSecret: "{{ .client_secret }}"
        redirectURL: https://gitops.${SECRET_DOMAIN}/oauth2/callback
        customScopes: openid,profile,email,groups
        claimGroups: groups
        claimUsername: preferred_username
        issuerURL: https://auth.${SECRET_DOMAIN}/application/o/authorize/
  data:
    - secretKey: client_id
      remoteRef:
        key: authentik-client-weave
        property: username
    - secretKey: client_secret
      remoteRef:
        key: authentik-client-weave
        property: password
