apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:vH9BYXC+uZa60V1A3Vjc3jE=,iv:yEchOFrMVFjWaPUeT+AkJZ9TcAaggvtZNahfCjQ1z44=,tag:44k8Yq5/Ew1GE7okMeqsew==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:uuPcLQLIgRY2,iv:pHoxYV+JqsBclaBTG+a9EXafhkDeu0+woowUYYGPbko=,tag:iPREwPUx9p/Lb2GPJvBMVw==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:QpwPzZiUbwHgismbW7B66sY=,iv:gjEcwkDcQDRf+v3k8WMIMx4+EBGD5YTV1MupZoE/exU=,tag:hlfhKugZyb3lyg/vutVVKg==,type:str]
    SECRET_NFS_PATH: ENC[AES256_GCM,data:5C7x3x6qcXzxsSgw4Q==,iv:Uw6k0+MWGRhdJ18yqfNFaNWZgCAfW0HCB6nrLS7XM7s=,tag:zn4MlJCjKsNCx3stK5hLEQ==,type:str]
    SECRET_UNPOLLER_USER: ENC[AES256_GCM,data:SrKFoo+QEj3omr0=,iv:gOmd8LL5J1VazVYqqfyYWK889Me4VKN1x+PMFDbfY5o=,tag:2YkFc1YfK3/8PXkmQmcR+Q==,type:str]
    SECRET_UNPOLLER_PASS: ENC[AES256_GCM,data:qU4hx10NB2T7o+8WbHikxz0zAkbzzR63dVS61HYucA==,iv:XpPDorie491qGJmEbH2aMinXVa2wRgzFAYNNAAplQ20=,tag:btbjwA5sTgPfWUJ0wqKJ2Q==,type:str]
    BW_CLIENTID: ENC[AES256_GCM,data:KStwznAK+0D+XmrGc++Zl3oXqp/tO92MiaGgNVO8Pf2bS6LcO3OsskE=,iv:XFy9H1VxL8ftaWGfDgLk4KzdtYYkGe9QX0LUXdweFR8=,tag:FxmJ2dmGe0N/IQWXCE04LQ==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:fBPTm/iAe7x0iqL+Z2hfXYnV/9YBnrWwHLDawLF/,iv:KRDih5JjqzHxsZVvU3ZILwM9V9PG/+RuRGdsdhvthYg=,tag:/MMYlg1xtDj6muDX0iLcmg==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:Do244XTc8p1nKdJ1N7a4hCKGawiRnw+pMETRxOHtWg==,iv:/RrnUsKaM60yuMUba4AdIIpqJLv3vcxlzn9YkYLkqX0=,tag:pOu8L5qxYYyUgV84uiP+RA==,type:str]
    BW_ORGANIZATION_ID: ENC[AES256_GCM,data:cUsimBAYm+QOETFmDjrQr5UEFL+7uYyUv5eWC7iUwcSo/MlC,iv:n1wogmUkwQ3vKFbO350uoiDcNj+cAqP2FqadCA9+LgQ=,tag:Cqu5fN6skW7nysaNyHisuA==,type:str]
    BW_COLLECTION_ID: ENC[AES256_GCM,data:LE2iJdDMUC9ZTXy8t7C8TUtvdIvNDSo/eK5F7QDV7NwInUBA,iv:GPzA8tx6spERq1H7eLELw2iPLYCvUOtKxrOdPiGLBtE=,tag:XpFNVCcank2pSn6KORhUfQ==,type:str]
    BW_GITHUB_OAUTH_CREDS_ID: ENC[AES256_GCM,data:5Oohz8+ZSfd6jXwDLoCo2d6R9Kgsoar2R2so9fvzrn81ZVhX,iv:LROKOVfU9/jWlGBnW8KEh0ff5sfOIoOCc3msCilxd88=,tag:jEMdZORgk0xHYkPJX987QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-03T22:41:38Z"
    mac: ENC[AES256_GCM,data:326PYGFIFzwCPHOBNqsEL/ZCaghDF2HrJ2j5UVMHaBV8nOUq5cO9e42Algi20v4wuknB+3Eqljwtsap8siB/FQXNxG1MY/UmKkExkYxBKztc2nNObPeNhRNj+pigzL4OBa/eDJlYDhTHnJ9qmdV5aw8uRAOswJZsZCXRdYd20Z4=,iv:HpiPWnhJh0CfTBwdkY96c8a/4gEFkHkjutYLjJbf6VU=,tag:xEifHJqDI0NpuDdJX6eoCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
