apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings-user
    namespace: flux-system
data:
    SETTINGS_PLACEHOLDER: ENC[AES256_GCM,data:jQKrCli4fCfYrprDblk=,iv:WShE0hkMqF5lHkccc7blQFVtGbs+Wx3THnF//Pc8PWE=,tag:fAOi/BYeoogs6EtzDHNWhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-03T22:42:18Z"
    mac: ENC[AES256_GCM,data:SSI83EIsyRY66y2ybNsVEVwKZfrpugsIICOrXYqzNU6gMztA4VULjwHl05i8hm4QJKk3BErR14c0HMU0kJbF0vDI/JIUMv4xqt9vRK1SEH+/15jooa0amILEGB0e+TcYomP9XAaJMYrkS/UzpDCXerm7BwOhd8ZOSha7ev+gv/c=,iv:OTN3I8ebHh8LmdiFnHwMX4Y1bp/dOc07C0OfNknoN30=,tag:Vpfcre7xPxPHB+eJedH9cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
