apiVersion: ENC[AES256_GCM,data:aG8=,iv:GnpKaIdeG7km8/x7Q5ZXHpnk65iWJjYh66NNH5BnLDE=,tag:EBI5P7t3+lHvltbcnu4TFw==,type:str]
kind: ENC[AES256_GCM,data:4WGrpnCFMaQo,iv:dcqt2pmrb+2j6ZOS1pYOu2lr73UDN5FW0uxbkCvf+5w=,tag:ldp5BGWmIvn5YBmopwTC4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VOaqCUpBTfbYf0g4oOAxjg==,iv:8OtL8cJUduSG1h+fPEpdzGeHsA/ntqLI8Zf73FGU/M8=,tag:a+YdTGiyuXt6NqDwZ7KCsg==,type:str]
    namespace: ENC[AES256_GCM,data:4Nf5z0RCLUZIKZE=,iv:PZE32WCtB8Uuahujxjkotmq8gH7RNIQVeicH+SPAuz4=,tag:tMA7aG6B55528JEQR7F0KA==,type:str]
data:
    BITWARDEN_APP_ID: ENC[AES256_GCM,data:seTkkj4MuPg10I11vkoBtdZhHmQ1W15rBvEP8VQ09psTS1kb6CPR7yvEeaAG7UVtyg==,iv:DvbgD8ZK/jgJJHfm31iZwmJcDtfwsx+Xqa1hB8TDp+U=,tag:aGlvkTL48hBaYrdY+g55zA==,type:str]
    CLUSTER_CIDR: ENC[AES256_GCM,data:BkMBcXETrBglLmcJ,iv:3D5JAyUdSTUW8ne0G4zVHyxpfGCq9/pV1+B8nyJNaps=,tag:mrmN9FHMCImIg7XciPukSQ==,type:str]
    CLUSTER_CIDR_V6: ENC[AES256_GCM,data:FgoeRCJ07Ndn7mbF/CthwWMyqHRmY44xSBM=,iv:RCSeU8qc0ajHYQrn8ex7NHxCS1Hm2G7pRSQ8PR9GJFw=,tag:kiDxiHAEfDCg0QHmG+PJqg==,type:str]
    CLUSTER_LB_EMQX: ENC[AES256_GCM,data:BF03ds7p0ddkmcpNQ5E=,iv:L81BpYwPrg1lrqL8tA0bsGosJqh7KHaysUwy+7MSDho=,tag:xqV2X9RJ9OmF83JM4A0stQ==,type:str]
    CLUSTER_LB_UNIFI: ENC[AES256_GCM,data:eRHGYowmNYSIx9UBnOk=,iv:xrBw2mox9QwuglOrfHeQgS+x82p++VcTEfpIt1cQekg=,tag:kxBxR4OgWg1WUYG4NZ6MfA==,type:str]
    CONTROLLER_IP_1: ENC[AES256_GCM,data:y1e0uD2xmpRv7zxpTg==,iv:jhVppGVzPxfz0aM4+dQzm8lcbvSiEHIlHscGlolYdnw=,tag:XrPjTD/46/vNeIqzFWNnqQ==,type:str]
    CONTROLLER_IP_2: ENC[AES256_GCM,data:qQNb9DplCvT2xP+IBQ==,iv:Em+vtgwTTnJDlPWRFGNFOXcNKAln69Z9HZ6PSriS4BA=,tag:05+qoTQq5xdXZo6TTK5X2Q==,type:str]
    COREDNS_ADDR: ENC[AES256_GCM,data:4YR6Wm7pZ4Wa2w==,iv:pyRABydfiVEgBakIRimpMySKB0vuJLq7ClavNkpYjO0=,tag:dGn085SOcMrrZkcHknRDaQ==,type:str]
    EXTERNAL_PROXY_ADDR: ENC[AES256_GCM,data:3KZq3q9MD/bq+AJ0zPU=,iv:U5jfmgg1QSaNdZVufgOAv6aKA44invezrw7KOY1EyDc=,tag:mJ5SOFceo4N5ZIwGgRv1Hg==,type:str]
    GATEWAY_ADDR: ENC[AES256_GCM,data:pHDTqOJtWH/MDT9FZTQ=,iv:GvKaKXPVB8ZJuKIsGMme9Sku7P++dtK3BS4l1K5+dsg=,tag:0Jvcho66UpIS/jWqVciljw==,type:str]
    INTERNAL_PROXY_ADDR: ENC[AES256_GCM,data:fmcVgQkEg7jRIBoWmPk=,iv:64IhmIr0p0/JqilIAVdK3PHmWt61TxQDRQpoV75/qZk=,tag:QaqU+6l2gbXH3RsbQQk7lw==,type:str]
    KUBE_VIP_ADDR: ENC[AES256_GCM,data:trjPlr8UheNYBj8KhYk=,iv:ABPNrglK7/fbRiXgJLWGY859rIux3fE9M0JgA4MOPN0=,tag:HB6ajh2NEjPIFRULvLM/LQ==,type:str]
    LB_CIDR_V4: ENC[AES256_GCM,data:Uxoudl7cWGuZXgzUkfLXz+4=,iv:tkYnk4R3vuISTm2/mnMEejyE6qWQaKYYs2HOva06wIQ=,tag:4oGiwVJGfIG67wqY0K9TDw==,type:str]
    LB_CIDR_V6: ENC[AES256_GCM,data:hqkTLMS/waB3LHBFIl9QjjHZ6BRot5UqXTnxbT0c,iv:+D2AreN7sRARkPF+xfboebrMEpIYSac77nXZoHIVnB0=,tag:jE0RZmiQ61BaX5dZC7zbLA==,type:str]
    NFS_SUBDIR_PATH: ENC[AES256_GCM,data:4ERwNHCEAF/PBN2UTzNXFaKFlDLxnfFge67j6iprmb8f4EoCZ6QfsRTNQC5ghr5EpA5mYbaSoGf5bYgf9VXtqudScx/m,iv:Du8IZfrjbAQgYM/jdbw9y4W1VHZpsgNrZwearQNhamk=,tag:q5jQwat81nrCAtPuXbzYfA==,type:str]
    NODE_CIDR: ENC[AES256_GCM,data:9t0MC9ncwngMFonjpbAANQ==,iv:kO9kDcuXWY8a3Pki3T5Xx3OAq1cMkTRBb1YDVVLfpug=,tag:r3jVXvMybgFhXEq0nXLGxA==,type:str]
    PIHOLE_ADDR: ENC[AES256_GCM,data:ecy5k/vEaca0itH57gg=,iv:zeMoFRP5ZDYoHP7G1hh4TQSxIFiAXQ2X13sn+W1VWMc=,tag:kFennTGyDIH1gNtFIZ7Dhw==,type:str]
    SERVICE_CIDR: ENC[AES256_GCM,data:6KoqMo6xmaWtWMML,iv:GTtAD3R5/xMCLDHEvOE0bb1V1tqu9fHAf/7+bxp1wzM=,tag:gh0AqS8Q2VW/kKeYFvLLiA==,type:str]
    SERVICE_CIDR_V6: ENC[AES256_GCM,data:bmO8zeBPebbBiX/M1+wycNId1abRL3AQSrfr,iv:1jwAG1IJW6/zQsLFepQgJhEtas+WBxs+UnRUtlijnO8=,tag:fJYDQP/g+ppZNq2Mw2RyCg==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:ijvc0NhXYDDCQRQVLjzsyQ==,iv:b99O9lDiHoMtmVqp77tocXxtnfGYMUzUEiB6buDjgs8=,tag:VMC8R8kAMKC+IGAja+0IUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pr4mejfd5gvq7fvkhgs534dftetx83564rj4j2y0hat6eucjl49qp60ag5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVU5UWDVnWlZEWEcyTk5v
            ek1lSHMxc3VXcG1DQWZ1c1pjdmFLdjZFSkE4Cnd1RE1YSzRmQkRqRk80UEkrZkMw
            eHIrdXZnVE1oZVlOaDlhYzlGOXFqejQKLS0tIHdtZUJOdExWWTNpalN4MU5xZW4z
            VGhyYjVnaDN1UmlKN1RlRmR5czVxM1UKn36arzluQG8pCgi3oeHIsitieCKn61PF
            vDL7NTRoYB+TV9RS+ReL2zvaleMqM4FHSmc/pzB30bdi3OvMQY3iGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T03:13:17Z"
    mac: ENC[AES256_GCM,data:i4ToXa8/FXJPaNg8imXNUSTaSHtQsi4yDfYyIiXIevzPHMNCPfQYX9PQ7fvzOB/c0j3vNia0LLVxlf52kHrnTmfGUVXvoNSeUGvVUVjyqikBZx5MuIwN0Ow8wlxWHrONJL24qbuLUsrJvD4NY6uGPR6+1aSaSH5WZhSabY7FURc=,iv:vr2inb0d+iCY8k98LV6YFH6pXHdqfqB3rOLQrHB2TJk=,tag:09LamUBAR3/52T0WuYvCVw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
