apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:/K3M98FD0X5F+WmK,iv:WRmqwraq/RbUFHzio16B/5DVSJNdLLNENpqsNj8gnt0=,tag:9oY9zdvzeB69UhXOPtGFNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-03T22:42:01Z"
    mac: ENC[AES256_GCM,data:QSGDRqQTvk++UKcOj4nw0i/8vKIqrRDxtko9r0DEWhyZ3wsOM9uSLbWo3R0nMB1c7szmrgktWj/jKqadZ+JXh2qHe0t874I6xzs6CmcwUHN6Nt3MikDWYyLLgZ+1FH/Fw/rCmxfjUpJMJ/H+M8Hh8TjVam3EOvsZPg7UBrXii4Q=,iv:oE4j6hte8g8Ub5qOCHRqMN7q4fNoWGkLnx2FDuf+Vwg=,tag:Nmc2wd2muMy9trCSOJ9Gjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
