apiVersion: ENC[AES256_GCM,data:4wk=,iv:vnC+zwYzMu0HtS3Vo6duc0mtHGaNrzbdghI4HAy6PX8=,tag:pbm4nJfuB43t0SBaqUTbhg==,type:str]
kind: ENC[AES256_GCM,data:b5olk46q,iv:iicNaHQ/1LMsFXseU0N4YUuJfMYqQXu4qQSSmA0cOpE=,tag:yyKrfGoR5qDcD0iA8jCNFA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fhL2NIP9UggHgDXuJTAn,iv:F1mMRsDufBCCdkTd3v6XbSZ2i4QpbEhdtRSz9SXlELM=,tag:owJV/VD1v8M+eTbn29dEZg==,type:str]
    namespace: ENC[AES256_GCM,data:O4zQ7RGS5FT+by0=,iv:bVE+M1baWi1q22HMJsmd0cgJcuj5YvhF2tiwcQiDjf4=,tag:ZACeb5fidVgiRq2mjeZerA==,type:str]
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ADCHwLJJCkYgDoKZjfFYQEA=,iv:4O6k0ShjjQhZymoqVvOwxlOHjhwUkBn/TbcHYgq7tjY=,tag:FlCBidBq6znCY3Xlg9SadQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:bqtN1+bRmawc,iv:ZsAiG/Tg644HL7nYYvkuYagBKmf0FNljsu20h9F4eRM=,tag:9oQeHmryPOQdaJLmLUD+YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pr4mejfd5gvq7fvkhgs534dftetx83564rj4j2y0hat6eucjl49qp60ag5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVzd5bXpDZDdlM3QwK3Av
            elBvdmZVS3Fjc2l0dmpjZk9uaUgwT2M2UVhRCkFTMklFR3hoY1VjOGtCWldVK0Jo
            ckhOY2lUMlhLK1hJRWZQd0hQejRySGsKLS0tIFRrNHgwODNTZG9kbkNOZ0hMQUJ0
            ZFB5TlZpSjZ6dVRuN0tYeVlENERZQmMKDB0THh+vWM87eb8ZqYKC/O8WdMAes1ra
            H4IgmsaGLj4v9hf4HMnN3bV9vrdk4IYQXjSxkX7x1YDJGIRHtdMAAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-17T15:03:37Z"
    mac: ENC[AES256_GCM,data:TxUr55H9czS2er5kKab4wHwWyUsMfgB5CLCXUGkeuTT9ebrwQcLzPLo9BguGrUVPGOJH1ygPNZDrMkztz4wcbMiQfmf5KO0NrCTzHeS29Dw0BxiM0jwLfJBNb3kiREk/d6KjlCuTtv1I32p/nIj9ARC5mHnjcPzc8sQ8p3TEjlE=,iv:9fQm2teTDp6StvXjrqtIu8n61ieQRT4CQvS4/ZeH/dE=,tag:GpsOrPKPJGob4ZQdHuI1Cw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
