---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: terraform
  namespace: flux-system
spec:
  interval: 15m
  url: oci://ghcr.io/jokajak/manifests/terraform
  ref:
    tag: main
