---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tf-bitwarden-pv
  namespace: flux-system
spec:
  capacity:
    storage: 1Gi # Should match the size specified in the PVC
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-dynamic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tf-bitwarden-pvc
  namespace: flux-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust the storage size as needed
