---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: authentik
  namespace: flux-system
spec:
  suspend: false
  approvePlan: auto
  storeReadablePlan: human
  interval: 15m
  path: ./authentik
  dependsOn:
    - name: bitwarden
  sourceRef:
    kind: OCIRepository
    name: terraform
    namespace: flux-system
  writeOutputsToSecret:
    name: authentik-outputs
  varsFrom:
    - kind: Secret
      name: cluster-secrets
      varsKeys:
        - BW_ORGANIZATION_ID:organization_id
        - BW_COLLECTION_ID:collection_id
        - SECRET_DOMAIN:domain
    - kind: Secret
      name: bitwarden-outputs
      varsKeys:
        - authentik_credentials_id:authentik_credentials_id
  runnerPodTemplate:
    spec:
      env:
        - name: BITWARDENCLI_APPDATA_DIR
          value: "/.bitwarden/"
      volumeMounts:
        - name: sops
          mountPath: /home/runner/.config/sops/age/keys.txt
          subPath: keys.txt
        - name: bitwarden-appid
          mountPath: /.bitwarden/data.json
          subPath: data.json
        - name: bitwarden-config-dir
          mountPath: /.bitwarden/
      volumes:
        - name: sops
          secret:
            secretName: sops-age
            items:
              - key: age.agekey
                path: keys.txt
        - name: bitwarden-appid
          configMap:
            name: cluster-settings
            items:
              - key: BITWARDEN_APP_ID
                path: data.json
        - name: bitwarden-config-dir
          emptyDir: {}
