---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: bitwarden
  namespace: flux-system
spec:
  suspend: false
  approvePlan: auto
  interval: 15m
  path: ./bitwarden
  sourceRef:
    kind: OCIRepository
    name: terraform
    namespace: flux-system
  writeOutputsToSecret:
    name: bitwarden-outputs
  varsFrom:
    - kind: Secret
      name: cluster-secrets
      varsKeys:
        - BW_ORGANIZATION_ID:terraform_organization
        - BW_COLLECTION_ID:collection_id
  runnerPodTemplate:
    spec:
      volumeMounts:
        - name: sops
          mountPath: /home/runner/.config/sops/age/keys.txt
          subPath: keys.txt
      volumes:
        - name: sops
          secret:
            secretName: sops-age
            items:
              - key: age.agekey
                path: keys.txt
