---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: cloudnative_pg credentials
        property: username
    - secretKey: password
      remoteRef:
        key: cloudnative_pg credentials
        property: password
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-pgsql
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        minio_s3_access_key: |-
          {{ .minio_user }}
        minio_s3_secret_access_key: |-
          {{ .minio_secret }}
  refreshInterval: 15m
  data:
    - secretKey: minio_user
      remoteRef:
        key: minio-tf-databases
        property: username
    - secretKey: minio_secret
      remoteRef:
        key: minio-tf-databases
        property: password
