---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: loki-bucket
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: access_key_id
      remoteRef:
        key: minio-tf-logs
        property: username
    - secretKey: secret_access_key
      remoteRef:
        key: minio-tf-logs
        property: password
