apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-webhook-henet-secret
    namespace: cert-manager
data:
    password: ENC[AES256_GCM,data:69erPiUrS+89V0ep796D++nIjPvtpoHU,iv:VOPeOwUpohSuezPHYtZquknAX/qaXuP/Vs4+K2qcVzQ=,tag:YPtsJL6cmzzjNWo/6LlgAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pr4mejfd5gvq7fvkhgs534dftetx83564rj4j2y0hat6eucjl49qp60ag5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWjY1c1Q0S3JqVVdCdW1s
            RmNFZUZVN2xtMjdpMC96RU9BdUVzdXJ0c0NjCk1JalhMZmlac056VFRDY2t0ZlRx
            b2k1aVFqSm9xRTg4NnhyazdaZWN4MHMKLS0tIE00dnlGbnVEL2xCS0RSanNUeDNQ
            RHJvNDNrSWw5N240Tk1MRVpGYVI4TXMKSD3oE1p/LxkOdrPwPcUgvgL3XDIBApUS
            A6ScvnodtFjV1OWeI4F0MOJRDodJudv6vSYBDAgCmMclTE2oJdizUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-02T15:19:01Z"
    mac: ENC[AES256_GCM,data:jSp7iB4DetkDqUZpyXmB7swvKQpQz/JXGOSKywLrRISHjfNehYuWNXx2/91M1fAYRW0Bvkog5WL6NeDTM/mn3YXcU1/p8yjb88oWVRTISq81SjseoZKcQt7oZm6cc6odBXi9pdkUBtxnTd9GrMduIXENdKmznDcB1S0Y6/Lw3ik=,iv:t/KLYpgUcnJ2kZqP+OZ6YBsVW6NIjcK6gGOUOeC5UQ4=,tag:w92jFGvBcXKZY2yUPBAT+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
