---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-secrets
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        prom-token: |-
          {{ .hass_prometheus_token }}
  refreshInterval: 15m
  data:
    - secretKey: hass_prometheus_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: home assistant
        property: hass_prometheus_token
