---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        type: statefulset
        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2023.11.3
            env:
              TZ: "UTC"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: 8123
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: "vscode-icons:file-type-homeassistant"
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: wildcard-cert-tls
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant
        globalMounts:
          - path: /config
    metrics:
      enabled: true
      # serviceMonitor:
      #   bearerTokenSecret:
      #     name: "prometheus-secrets"
      #     key: "prom-token"
      prometheusRule:
        enabled: true
        rules: []
