---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sops-age  # store the age key in bitwarden
  namespace: kube-system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        age.key: |-
          {{ .age }}
  refreshInterval: 15m
  data:
    - secretKey: age
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: # tbd
