---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tf-controller
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    awsPackage:
      install: false
    runner:
      image:
        repository: ghcr.io/jokajak/tf-runner-bw
        tag: v0.16.0-rc.2_1.6.1_2023.9.0
