---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: tf-controller
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: weaveworks
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    awsPackage:
      install: false
    runner:
      grpc:
        # due to received message larger than max (5685919 vs. 4194304)
        maxMessageSize: 10
      image:
        repository: ghcr.io/jokajak/tf-runner-bw
        tag: v0.16.0-rc.2_1.6.1_2023.9.0
